
interface _GlobalComponents {
      'BaseTitle': typeof import("../components/BaseTitle.vue")['default']
    'HomeFeatured': typeof import("../components/HomeFeatured.vue")['default']
    'HomeTopRated': typeof import("../components/HomeTopRated.vue")['default']
    'PostList': typeof import("../components/PostList.vue")['default']
    'PostListHorizontal': typeof import("../components/PostListHorizontal.vue")['default']
    'PostListMinimal': typeof import("../components/PostListMinimal.vue")['default']
    'PostListSimple': typeof import("../components/PostListSimple.vue")['default']
    'PostListStacked': typeof import("../components/PostListStacked.vue")['default']
    'PostTags': typeof import("../components/PostTags.vue")['default']
    'SearchBox': typeof import("../components/SearchBox.vue")['default']
    'TheArticle': typeof import("../components/TheArticle.vue")['default']
    'TheFooter': typeof import("../components/TheFooter.vue")['default']
    'TheNav': typeof import("../components/TheNav.vue")['default']
    'UnoIcon': typeof import("../node_modules/.pnpm/@unocss+nuxt@0.46.5_rollup@4.16.4_vite@3.2.10_@types+node@20.12.7_terser@5.30.4__webpack@5.91.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.3/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyBaseTitle': typeof import("../components/BaseTitle.vue")['default']
    'LazyHomeFeatured': typeof import("../components/HomeFeatured.vue")['default']
    'LazyHomeTopRated': typeof import("../components/HomeTopRated.vue")['default']
    'LazyPostList': typeof import("../components/PostList.vue")['default']
    'LazyPostListHorizontal': typeof import("../components/PostListHorizontal.vue")['default']
    'LazyPostListMinimal': typeof import("../components/PostListMinimal.vue")['default']
    'LazyPostListSimple': typeof import("../components/PostListSimple.vue")['default']
    'LazyPostListStacked': typeof import("../components/PostListStacked.vue")['default']
    'LazyPostTags': typeof import("../components/PostTags.vue")['default']
    'LazySearchBox': typeof import("../components/SearchBox.vue")['default']
    'LazyTheArticle': typeof import("../components/TheArticle.vue")['default']
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default']
    'LazyTheNav': typeof import("../components/TheNav.vue")['default']
    'LazyUnoIcon': typeof import("../node_modules/.pnpm/@unocss+nuxt@0.46.5_rollup@4.16.4_vite@3.2.10_@types+node@20.12.7_terser@5.30.4__webpack@5.91.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.3/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BaseTitle: typeof import("../components/BaseTitle.vue")['default']
export const HomeFeatured: typeof import("../components/HomeFeatured.vue")['default']
export const HomeTopRated: typeof import("../components/HomeTopRated.vue")['default']
export const PostList: typeof import("../components/PostList.vue")['default']
export const PostListHorizontal: typeof import("../components/PostListHorizontal.vue")['default']
export const PostListMinimal: typeof import("../components/PostListMinimal.vue")['default']
export const PostListSimple: typeof import("../components/PostListSimple.vue")['default']
export const PostListStacked: typeof import("../components/PostListStacked.vue")['default']
export const PostTags: typeof import("../components/PostTags.vue")['default']
export const SearchBox: typeof import("../components/SearchBox.vue")['default']
export const TheArticle: typeof import("../components/TheArticle.vue")['default']
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const TheNav: typeof import("../components/TheNav.vue")['default']
export const UnoIcon: typeof import("../node_modules/.pnpm/@unocss+nuxt@0.46.5_rollup@4.16.4_vite@3.2.10_@types+node@20.12.7_terser@5.30.4__webpack@5.91.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.3/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyBaseTitle: typeof import("../components/BaseTitle.vue")['default']
export const LazyHomeFeatured: typeof import("../components/HomeFeatured.vue")['default']
export const LazyHomeTopRated: typeof import("../components/HomeTopRated.vue")['default']
export const LazyPostList: typeof import("../components/PostList.vue")['default']
export const LazyPostListHorizontal: typeof import("../components/PostListHorizontal.vue")['default']
export const LazyPostListMinimal: typeof import("../components/PostListMinimal.vue")['default']
export const LazyPostListSimple: typeof import("../components/PostListSimple.vue")['default']
export const LazyPostListStacked: typeof import("../components/PostListStacked.vue")['default']
export const LazyPostTags: typeof import("../components/PostTags.vue")['default']
export const LazySearchBox: typeof import("../components/SearchBox.vue")['default']
export const LazyTheArticle: typeof import("../components/TheArticle.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyTheNav: typeof import("../components/TheNav.vue")['default']
export const LazyUnoIcon: typeof import("../node_modules/.pnpm/@unocss+nuxt@0.46.5_rollup@4.16.4_vite@3.2.10_@types+node@20.12.7_terser@5.30.4__webpack@5.91.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.3/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@unocss+reset@0.46.5_change-case@4.1.2__gltip53y3rotuw3va3yfzoahxy/node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
